[package]
name = "magnetar"
version = "0.0.5"
description = "magnetar"
authors = ["Bamboooz"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "dialog-open", "fs-read-file", "fs-remove-file", "fs-write-file", "protocol-asset", "fs-create-dir", "fs-exists", "shell-open", "system-tray", "window-hide", "global-shortcut-all", "window-close", "window-set-focus", "window-show"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-positioner = "1.0.5"
window-shadows = "0.2.2"
winreg = "0.52.0"

[features]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = 3
strip = true 
lto = true
codegen-units = 1
panic = "abort"
